[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
slot_machine = "6rysbpjLEHyNinMSunnUX52G2a6N7sRWxLgVGAmhPU3Y"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx tsc && npx mocha -t 1000000 dist/tests/**/*.js"
